### ISSUE TITLE
Call to immediate function is not a constant expression

### ISSUE THREAD

**Issue by cruiser127** [shuffle2/LpcAnalyzer#6]
When attempting to build with 17.6.3, lines 210 and 218 throw this error. When searching online some say this is a bug introduced recently in VS and is pending a fix while others say there's a new way to implement std:format. Could you give some insight to this issue?

**Comment by shuffle2** [comment]
thanks, should be fixed by https://github.com/shuffle2/LpcAnalyzer/commit/043321b615130d0d7d24fbcd0f5e65e9c8325722 let me know if not (I only made it compile, didn't test at runtime)
